### ISSUE TITLE
question in coarsen.py

### ISSUE THREAD

**Issue by PlusRoss** [CRIPAC-DIG/H-GCN#2]
Hi,

In coarsen.py, the normalized_adj_wgt function is written as:
```
def normalized_adj_wgt(graph):
    adj_wgt = graph.adj_wgt
    adj_idx = graph.adj_idx
    norm_wgt = np.zeros(adj_wgt.shape, dtype=np.float32)
    degree = graph.degree
    for i in range(graph.node_num):
        for j in range(adj_idx[i], adj_idx[i + 1]):
            neigh = graph.adj_list[j]
            norm_wgt[j] = adj_wgt[neigh] / np.sqrt(degree[i] * degree[neigh])
    return norm_wgt
```   

Should the following line:
```
norm_wgt[j] = adj_wgt[neigh] / np.sqrt(degree[i] * degree[neigh])
```
be:
```
norm_wgt[j] = adj_wgt[j] / np.sqrt(degree[i] * degree[neigh])
```
?

**Comment by FenyuHu** [comment]
Hi, thank you for your question.

For the i-th node, it has ( adj_idx[i + 1] - adj_idx[i ] )  edges.  And thus in the inner-loop, the j-th edge has two vertices, which are node "i" and node "neigh".   The edge weight of the  j-th edge is stored in adj_wgt[neigh] . So there is no problem with the initial code.

Please refer to the function "read_graph_from_adj(adj,dataset_name)" in utils.py for more details for the construction of adj_idx, adj_list, and adj_wgt.

Please feel free to contact me if you have any other questions. Thanks.

**Comment by PlusRoss** [comment]
Thanks for your reply! But I'm still confused about this:

In your Graph.__init__() function, the adj_wgt is defined as:
```
self.adj_wgt = np.zeros(edge_num,
                           dtype=np.float32)  # same dimension as adj_list, wgt on the edge. CAN be float numbers.
```
The shape of adj_wgt is edge_num, not node_num, so "neigh" should not be the index of adj_wgt. And in the function read_graph_from_adj(adj,dataset_name):
```
graph.adj_list[edge_cnt] = neigh # self-loop included.
graph.adj_wgt[edge_cnt] = wgt
graph.degree[idx] += wgt
```
The adj_list and adj_wgt use the same index, which means the edge weight of the j-th edge is stored in adj_wgt[j]. 

Is there anything wrong?

**Comment by CHELSEA234** [comment]
@FenyuHu  Thank you for the well-written code and impressive work. However, I agree with @Maysir  on `norm_wgt[j] = adj_wgt[j] / np.sqrt(degree[i] * degree[neigh])`. 

`adj_weight` has length of edge_num, in your way, only first `node_num` will be updated. I have noticed this and was about to start an issue, thank again @Maysir for this thread. I hope people who use your code later can avoid such mistake!

**Comment by FenyuHu** [comment]
@CHELSEA234 @Maysir  Thank you for your question again and sorry for the late reply! I check the code again and  find that you are right. I will fix this bug and retune the parameters.

**Comment by PlusRoss** [comment]
Thanks! And I really appreciate this excellent work. @FenyuHu
