### ISSUE TITLE
The graph in H-GCN could be changed during the coarsening?

### ISSUE THREAD

**Issue by trichtu** [CRIPAC-DIG/H-GCN#5]
Since we have the graph structure that are diferent from sample to sample. But these graph might be followed with some principle. Could H-GCN be used with these data? Since your code might predefined the graph and then training.

**Comment by FenyuHu** [comment]
Technically, yes. You can first preprocess each graph and coarse them accordingly. I suppose you are dealing with tasks like graph classification (we focus on node classification task where there is only one graph).  So I recommend you referring to diffpool, Self-Attention Graph Pooling or Graph-unet for more details. The key difference is that, these methods learn the coarsening matrix for each graph, but we obtain the coarsening matrix by preprocessing.
