### ISSUE TITLE
粗化终止条件？

### ISSUE THREAD

**Issue by Wangpeiyi9979** [CRIPAC-DIG/H-GCN#6]
您好，文中好像没有给出粗化的终止条件，请问是一直粗化到只剩一个节点吗

**Comment by FenyuHu** [comment]
是的，对应实现在coarsen.py的generate_hybrid_matching函数中。从第42行开始对每个节点按度从小到大的顺序做遍历，设置了matched标记，所有节点被标记过之后循环就停止了。
