### ISSUE TITLE
准确率？

### ISSUE THREAD

**Issue by huigoing** [CRIPAC-DIG/H-GCN#7]
作者您好！

我用您代码的默认参数在cora数据集上只跑出0.826, 远没有达到您论文上写的0.845。

请问您的参数怎么设置的？

谢谢！

**Comment by huigoing** [comment]
我用您提供的以下3条默认参数， 没有一个跑出您论文中写的准确率，每一个均相差2个百分点以上。

请问您能提供真实的参数吗！

谢谢！

python train.py --dataset cora --epochs 60 --early_stopping 1000 --coarsen_level 4 --dropout 0.85 --weight_decay 7e-4 --hidden 32 --node_wgt_embed_dim 8 --seed1 156 --seed2 136

python train.py --dataset citeseer --epochs 200 --early_stopping 60 --coarsen_level 4 --dropout 0.85 --weight_decay 7e-4 --hidden 30 --node_wgt_embed_dim 15 --seed1 156 --seed2 156

python train.py --dataset pubmed --epochs 250 --early_stopping 1000 --coarsen_level 4 --dropout 0.85 --weight_decay 7e-4 --hidden 30 --node_wgt_embed_dim 8 --seed1 156 --seed2 136

**Comment by FenyuHu** [comment]
Hi, have you reproduce the results? Please refer to https://github.com/CRIPAC-DIG/H-GCN/issues/1 for more information.

**Comment by FenyuHu** [comment]
Thank you for your feedback in email！ The version of numpy also impacts the results of random seeds. We use numpy 1.19.1 for experiments.
