### ISSUE TITLE
I use your model in my dataset，so how to modify the read_graph_from_adj function?

### ISSUE THREAD

**Issue by tanjia123456** [CRIPAC-DIG/H-GCN#9]
Hello, thanks for your contribution. I used your network on my dataset, there's no .graph file. So how to modify the  read_graph_from_adj function in utils.py?

**Comment by FenyuHu** [comment]
Sorry, I am very busy recently. I will check the code and give more suggestions at the end of this month.

**Comment by tanjia123456** [comment]
> Sorry, I am very busy recently. I will check the code and give more suggestions at the end of this month.

`def generate_adj(edge_path):
    '''return one subject's adj,features,labels'''
    edges = pd.read_csv(edge_path, encoding='utf-8', header=None,
                        sep=' ', names=['source', 'target'])
    assert not edges.isnull().sum().sum()
    graph = nx.Graph()
    edge_tuple = [(row.source, row.target) for row in edges.itertuples(index=False)]
    graph.add_edges_from(edge_tuple)
    adj_index = nx.adjacency_matrix(graph)

    return adj_index`

adj = generate_adj('data/subject1/lhedges.txt')#(10242, 10242) <class 'scipy.sparse.csr.csr_matrix'>
the edge file is [here](https://github.com/tanjia123456/Brain/blob/main/lhedges.txt)

**Comment by tanjia123456** [comment]
Hello，do you have an idea now？

**Comment by FenyuHu** [comment]
Sorry for late reply. It seems like you have some trouble in constructing .graph file.  But I cannot figure out the file you provided. Please contact me through emails at fenyu.hu##cripac.ia.ac.cn  （##--> @）

**Comment by FenyuHu** [comment]
We are happy that the problem was solved.
